# Generated by Django 4.0.1 on 2022-06-15 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='has_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
