# Generated by Django 4.0.1 on 2022-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stripe_id',
            field=models.CharField(max_length=50),
        ),
    ]
