# Generated by Django 4.0.1 on 2022-06-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stripe_id',
            field=models.SlugField(max_length=255),
        ),
    ]
