# Generated by Django 4.0.1 on 2022-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transaction_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
