# Generated by Django 4.0.1 on 2022-02-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
