# Generated by Django 4.0.1 on 2022-02-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0007_alter_address_address_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('zipcode', 'landmark', 'user')},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ManyToManyField(blank=True, to='userlogin.Category')),
            ],
        ),
    ]
