# Generated by Django 4.0.1 on 2022-03-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0012_alter_cart_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
