# Generated by Django 4.0.1 on 2022-03-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0013_alter_cartitem_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='ProductCart',
        ),
        migrations.RenameModel(
            old_name='CartItem',
            new_name='ProductCartItem',
        ),
    ]
