# Generated by Django 4.0.1 on 2022-03-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0014_rename_cart_productcart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCart',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='ProductCartItem',
            new_name='CartItem',
        ),
    ]
