# Generated by Django 4.0.1 on 2022-03-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0016_productcartitem_productcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='productcartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
        migrations.DeleteModel(
            name='ProductCartItem',
        ),
    ]
