# Generated by Django 4.0.1 on 2022-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0021_alter_address_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='myuser',
            name='code',
            field=models.IntegerField(default=1),
        ),
    ]
