# Generated by Django 4.0.1 on 2022-06-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0023_name_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='code1',
        ),
    ]
