# Generated by Django 4.0.1 on 2022-06-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0024_remove_myuser_code1'),
    ]
#
#     operations = [
#         migrations.RenameField(
#             model_name='myuser',
#             old_name='code',
#             new_name='code1',
#         ),
#     ]
