# Generated by Django 4.0.1 on 2022-03-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_price_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('placed', 'placed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
