# Generated by Django 4.0.1 on 2022-03-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_status_alter_cart_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PLACED', 'Placed')], default='OPEN', max_length=10),
        ),
    ]
